server:
  port: 8080 # Порт сервера
  error:
    include-message: always # Выводить сообщение в отловленной ошибке

application:
  max-allowed-books: 3 # настойка максимальное количество книг выданных читателю


spring:
  application:
    name: HomWor5
  datasource:
    url: jdbc:h2:mem:homework
    username: Bob
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop